version: "3.7"

services:

  webapp:
    container_name: offersproject_web
    tty: true
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./offersproject:/offersproject
    command: |
      sh -c
      "python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0:8000"
