# Generated by Django 3.2.3 on 2021-10-06 00:02

import django.core.validators
from django.db import migrations, models
import offers.models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='ordering',
            field=models.PositiveIntegerField(default=offers.models.get_max_categories_amount, validators=[django.core.validators.MaxValueValidator(offers.models.get_max_categories_amount), django.core.validators.MinValueValidator(1)]),
        ),
    ]
